classdef NeuroBits < handle
    %
    % NeuroBits
    %
    % widget based GUI for
    % user guided neuronal tree segmentation
    %
    % FolderBrowser
    % ImageBrowser
    % NeuroTree
    % NeuroPuncta
    % 
    % Georgi Tushev
    % sciclist@brain.mpg.de
    % Max-Planck Institute For Brain Research
    %
    
    properties (Access = private, Hidden = true)
        file
        ui_figure
        widget_FolderBrowser
        widget_ImageBrowser
        widget_NeuroTree
        widget_NeuroPuncta
        widget_BatchJoat
    end
    
    properties (Constant = true, Access = private, Hidden = true)
        
        GUI_WINDOW_POSITION = [0, 0.15, 0.15, 0.8];
        BACKGROUND_COLOR = [1, 1, 1]; % WHITE
        FOREGROUND_COLOR = [0.5, 0.5, 0.5]; % GRAY
        FONT_SIZE = 10;
        BORDER_WIDTH = 0.015;
        BORDER_HEIGHT = 0.015;
        
    end
    
    methods
        
        % method :: NeuroBits
        %  input :: class object
        % action :: class constructor
        function obj = NeuroBits()
            clc;
            close all;
            
            % initialize graphical user interface
            obj.renderUI();
            
            % initialize listeners
            addlistener(obj.widget_FolderBrowser, 'event_fileUpdated', @obj.fcnCallback_FileUpdate);
            
        end
        
        
        % method :: renderUI
        %  input :: class object
        % action :: render user interface
        function obj = renderUI(obj)
            
            
            %%% --- Main Figure --- %%%
            obj.ui_figure = figure(...
                'Visible', 'on',...
                'Tag', 'hNeuroBits',...
                'Name', 'NeuroBits',...
                'Units', 'normalized',...
                'Position', obj.GUI_WINDOW_POSITION,...
                'NumberTitle', 'off',...
                'MenuBar', 'none',...
                'ToolBar', 'none',...
                'Color', obj.BACKGROUND_COLOR,...
                'CloseRequestFcn', @obj.fcnCallback_CloseUIWindow);
            
            
            %%% --- Load Images --- %%%
            hPan_FolderBrowser = uipanel(...
                'Parent', obj.ui_figure,...
                'Title', 'Folder Browser',...
                'TitlePosition', 'lefttop',...
                'FontSize', obj.FONT_SIZE,...
                'BorderType', 'line',...
                'HighlightColor', obj.FOREGROUND_COLOR,...
                'ForegroundColor', obj.FOREGROUND_COLOR,...
                'BackgroundColor', obj.BACKGROUND_COLOR,...
                'Units', 'normalized',...
                'Position', uiGridLayout([5, 1],...
                                         [obj.BORDER_HEIGHT, obj.BORDER_WIDTH],...
                                         1, 1));
            obj.widget_FolderBrowser = WidgetFolderBrowser(...
                                       'Parent',hPan_FolderBrowser,...
                                       'Extension','*.lsm');
            
                                              
            %%% --- Browse Images --- %%%
            hPan_ImageBrowser = uipanel(...
                'Parent', obj.ui_figure,...
                'Title', 'Image Browser',...
                'TitlePosition', 'lefttop',...
                'FontSize', obj.FONT_SIZE,...
                'BorderType', 'line',...
                'HighlightColor', obj.FOREGROUND_COLOR,...
                'ForegroundColor', obj.FOREGROUND_COLOR,...
                'BackgroundColor', obj.BACKGROUND_COLOR,...
                'Units', 'normalized',...
                'Position', uiGridLayout([5, 1],...
                                         [obj.BORDER_HEIGHT, obj.BORDER_WIDTH],...
                                         2, 1));
            obj.widget_ImageBrowser = WidgetImageBrowser('Parent',hPan_ImageBrowser);
            
            
            %%% --- DrawTree --- %%%
            hPan_NeuroTree = uipanel(...
                'Parent', obj.ui_figure,...
                'Title', 'Neuro Tree',...
                'TitlePosition', 'lefttop',...
                'FontSize', obj.FONT_SIZE,...
                'BorderType', 'line',...
                'HighlightColor', obj.FOREGROUND_COLOR,...
                'ForegroundColor', obj.FOREGROUND_COLOR,...
                'BackgroundColor', obj.BACKGROUND_COLOR,...
                'Units', 'normalized',...
                'Position', uiGridLayout([5, 1],...
                                         [obj.BORDER_HEIGHT, obj.BORDER_WIDTH],...
                                         3, 1));
            obj.widget_NeuroTree = WidgetNeuroTree('Parent', hPan_NeuroTree);
            
            
            %%% --- Find Puncta --- %%%
            hPan_NeuroPuncta = uipanel(...
                'Parent', obj.ui_figure,...
                'Title', 'Neuro Puncta',...
                'TitlePosition', 'lefttop',...
                'FontSize', obj.FONT_SIZE,...
                'BorderType', 'line',...
                'HighlightColor', obj.FOREGROUND_COLOR,...
                'ForegroundColor', obj.FOREGROUND_COLOR,...
                'BackgroundColor', obj.BACKGROUND_COLOR,...
                'Units', 'normalized',...
                'Position', uiGridLayout([5, 1],...
                                         [obj.BORDER_HEIGHT, obj.BORDER_WIDTH],...
                                         4, 1));
            
            %%% --- Batch Processing --- %%%
            hPan_Batch = uipanel(...
                'Parent', obj.ui_figure,...
                'Title', 'Batch Job',...
                'TitlePosition', 'lefttop',...
                'FontSize', obj.FONT_SIZE,...
                'BorderType', 'line',...
                'HighlightColor', obj.FOREGROUND_COLOR,...
                'ForegroundColor', obj.FOREGROUND_COLOR,...
                'BackgroundColor', obj.BACKGROUND_COLOR,...
                'Units', 'normalized',...
                'Position', uiGridLayout([5, 1],...
                                         [obj.BORDER_HEIGHT, obj.BORDER_WIDTH],...
                                         5, 1));
            
        end
        
        
        % method :: initWidgetImageBrowser
        %  input :: class object
        % action :: initialize image browser image
        function obj = initWidgetImageBrowser(obj)
            
            % evoke load method in WidgetImageBrowser
            obj.file = obj.widget_FolderBrowser.list{obj.widget_FolderBrowser.index};
            obj.widget_ImageBrowser.loadImage(obj.file);
            
        end
        
        % method :: initWidgetNeuroTree
        %  input :: class object
        % action :: initialize neuro tree
        function obj = initWidgetNeuroTree(obj)
            
            % activate ui
            set(obj.widget_NeuroTree.ui_pushButton_SegmentTree, 'Enable', 'on');
            
            % pass current file name and figure to WidgetNeuroTree
            [path, name] = fileparts(obj.file);
            obj.widget_NeuroTree.path = path;
            obj.widget_NeuroTree.name = name;
            obj.widget_NeuroTree.ui_figure = obj.widget_ImageBrowser.ui_figure;
            obj.widget_NeuroTree.ui_axes = obj.widget_ImageBrowser.ui_axes;
            obj.widget_NeuroTree.ui_image = obj.widget_ImageBrowser.ui_image;
            
        end
        
        %%% -------------------------- %%%
        %%% --- CALLBACK FUNCTIONS --- %%%
        %%% -------------------------- %%%
        
        % callback :: CloseUIWindow
        %    event :: on close request
        %   action :: class detructor
        function obj = fcnCallback_CloseUIWindow(obj, ~, ~)
            
            if isgraphics(obj.ui_figure, 'Figure')
                delete(obj.ui_figure);
            end
            
            delete(obj);
        end
        
        % callback :: FileUpdate
        %    event :: on FileUpdated event from FileBrowser widget
        %   action :: load image in ImageBrowser widget
        function obj = fcnCallback_FileUpdate(obj, ~, ~)
            
            % initialize WidgetImageBrowser
            obj.initWidgetImageBrowser();
            
            % initialize WidgetNeuroTree
            obj.initWidgetNeuroTree();
            
        end
        
    end
    
end