classdef WidgetNeuroTree < handle
    %
    % WidgetNeuroTree
    %
    % GUI Widget for 
    % user guided neuro tree segmentation
    % exporting/loading and modifying segmented ROIs
    % automatic linking of parent/child hierarchy
    % creating a ROI labeled mask
    %
    % requires:
    %    class NeuroTreeROI
    %    readLSMInfo.m
    %    readLSMImage.m
    %    uiGridLayout.m
    %
    % Georgi Tushev
    % sciclist@brain.mpg.de
    % Max-Planck Institute For Brain Research
    %
    
    properties
        path
        name
        
        image
        mask
        tree
        
    end
    
    properties (Access = public, Hidden = true)
        
        %%% --- image figure handlers --- %%%
        ih_figure
        ih_axes
        ih_image
        
    end
    
    properties (Access = private, Hidden = true)
        
        %%% --- State Machine --- %%%
        state
        dilate
        indexBranch
        indexNode
        
        %%% --- UI components --- %%%
        ui_parent
        ui_panel
        
        ui_pushButton_SegmentTree
        ui_pushButton_SaveTree
        ui_pushButton_LoadTree
        ui_pushButton_LinkTree
        ui_pushButton_ViewMask
        ui_pushButton_DownMask
        ui_pushButton_UpMask
        
        ui_text_StatusBranch
        ui_text_StatusNode
        ui_text_StatusDepth
        ui_text_StatusLength
        ui_text_StatusDilate
        ui_text_StatusLinked
        
    end
    
    properties (Constant, Hidden)
        
        %%% --- UI properties --- %%%
        GUI_WINDOW_POSITION = [0, 0.455, 0.15, 0.40];
        BACKGROUND_COLOR = [1, 1, 1]; % WHITE
        FOREGROUND_COLOR = [0.5, 0.5, 0.5]; % GRAY
        GRID_MARGIN_H = 0.015;
        GRID_MARGIN_W = 0.015;
        FONT_SIZE = 8;
        
        %%% --- Tree Settings --- %%%
        MIN_DILATE_SIZE = 1;
        MAX_DILATE_SIZE = 30;
        
        %%% --- State machine --- %%%
        STATE_IDLE = 0;
        STATE_OVER_CLICK = 1;
        STATE_OVER_ROI = 2;
        STATE_MOVE_CLICK = 3;
        STATE_MOVE_ROI = 4;
        STATE_DRAWING_ROI = 5;
        
    end
    
    methods
        
        % method :: WidgetNeuroTree
        %  input :: varargin
        % action :: class constructor
        function obj = WidgetNeuroTree(varargin)
            
            % use parser
            parserObj = inputParser;
            
            % define inputs
            addParameter(parserObj, 'Parent', [], @isgraphics);
            
            % parse varargin
            parse(parserObj, varargin{:});
            
            % set UI parent
            if isempty(parserObj.Results.Parent)
                obj.ui_parent = figure(...
                    'Visible', 'on',...
                    'Tag', 'hDrawNeuroTreeUI',...
                    'Name', 'Draw Neuro Tree',...
                    'NumberTitle', 'off',...
                    'MenuBar', 'none',...
                    'ToolBar', 'none',...
                    'Color', obj.BACKGROUND_COLOR,...
                    'Units', 'normalized', ...
                    'Position', obj.GUI_WINDOW_POSITION,...
                    'CloseRequestFcn', @obj.fcnCallback_CloseUIWindow);
            else
                obj.ui_parent = parserObj.Results.Parent;
            end
            
            % set defaults
            obj.dilate = 5;
            
            % render UI
            obj.renderUI();
            
        end
        
        % method :: renderUI
        %  input :: class object
        % action :: render user interface
        function obj = renderUI(obj)
            
            hPanel = uipanel(...
                'Parent', obj.ui_parent,...
                'BorderType', 'none',...
                'BackgroundColor', obj.getParentColor(),...
                'Units', 'normalized',...
                'Position', [0, 0, 1, 1]);
            
            obj.ui_text_StatusBranch = uicontrol(...
                'Parent', hPanel,...
                'Style', 'Text',...
                'String', 'branch 0',...
                'BackgroundColor', obj.getParentColor(),...
                'HorizontalAlignment', 'center',...
                'FontSize', obj.FONT_SIZE,...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([8,3],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         1, 1));
            
            obj.ui_text_StatusNode = uicontrol(...
                'Parent', hPanel,...
                'Style', 'Text',...
                'String', 'node 0',...
                'BackgroundColor', obj.getParentColor(),...
                'HorizontalAlignment', 'center',...
                'FontSize', obj.FONT_SIZE,...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([8,3],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         2, 1));
            
            obj.ui_text_StatusDepth = uicontrol(...
                'Parent', hPanel,...
                'Style', 'Text',...
                'String', 'depth 0',...
                'BackgroundColor', obj.getParentColor(),...
                'HorizontalAlignment', 'center',...
                'FontSize', obj.FONT_SIZE,...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([8,3],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         1, 2));
            
            obj.ui_text_StatusLinked = uicontrol(...
                'Parent', hPanel,...
                'Style', 'Text',...
                'String', 'linked false',...
                'BackgroundColor', obj.getParentColor(),...
                'HorizontalAlignment', 'center',...
                'FontSize', obj.FONT_SIZE,...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([8,3],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         2, 2));                         
                                     
            obj.ui_text_StatusLength = uicontrol(...
                'Parent', hPanel,...
                'Style', 'Text',...
                'String', 'length[px] 0',...
                'BackgroundColor', obj.getParentColor(),...
                'HorizontalAlignment', 'center',...
                'FontSize', obj.FONT_SIZE,...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([8,3],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         1, 3));
            
            obj.ui_text_StatusDilate = uicontrol(...
                'Parent', hPanel,...
                'Style', 'Text',...
                'String', 'dilate[px] 0',...
                'BackgroundColor', obj.getParentColor(),...
                'HorizontalAlignment', 'center',...
                'FontSize', obj.FONT_SIZE,...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([8,3],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         2, 3));
            
            
                                     
            obj.ui_pushButton_SegmentTree = uicontrol(...
                'Parent', hPanel,...
                'Style', 'PushButton',...
                'String', 'Segment',...
                'Enable', 'off',...
                'Callback', @obj.fcnCallback_SegmentTree,...
                'Units', 'normalized',...
                'Position', uiGridLayout([4,2],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         2, 1));
                                     
            obj.ui_pushButton_SaveTree = uicontrol(...
                'Parent', hPanel,...
                'Style', 'PushButton',...
                'String', 'Save Tree',...
                'Enable', 'off',...
                'Callback', @obj.fcnCallback_SaveTree,...
                'Units', 'normalized',...
                'Position', uiGridLayout([4,2],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         3, 1));
            
            obj.ui_pushButton_LoadTree = uicontrol(...
                'Parent', hPanel,...
                'Style', 'PushButton',...
                'String', 'Load Tree',...
                'Enable', 'off',...
                'Callback', @obj.fcnCallback_LoadTree,...
                'Units', 'normalized',...
                'Position', uiGridLayout([4,2],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         4, 1));                         
                                     
            obj.ui_pushButton_LinkTree = uicontrol(...
                'Parent', hPanel,...
                'Style', 'PushButton',...
                'String', 'Link Tree',...
                'Enable', 'off',...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([4,2],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         2, 2));
            
           obj.ui_pushButton_ViewMask = uicontrol(...
                'Parent', hPanel,...
                'Style', 'PushButton',...
                'String', 'Show Mask',...
                'Enable', 'off',...
                'Callback', [],...
                'Units', 'normalized',...
                'Position', uiGridLayout([4,2],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         3, 2));
                                     
           obj.ui_pushButton_DownMask = uicontrol(...
                'Parent', hPanel,...
                'Style', 'PushButton',...
                'String', '<<',...
                'Enable', 'off',...
                'Callback', @obj.fcnCallback_SetMaskSize,...
                'Units', 'normalized',...
                'Position', uiGridLayout([4,4],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         4, 3));
            
           obj.ui_pushButton_UpMask = uicontrol(...
                'Parent', hPanel,...
                'Style', 'PushButton',...
                'String', '>>',...
                'Enable', 'off',...
                'Callback', @obj.fcnCallback_SetMaskSize,...
                'Units', 'normalized',...
                'Position', uiGridLayout([4,4],...
                                         [obj.GRID_MARGIN_H, obj.GRID_MARGIN_W],...
                                         4, 4));
          
        end
        
        
        % method :: getParentColor
        %  input :: class object
        % action :: returns value of Parent Color/BackgroundColor property
        function value = getParentColor(obj)
            if isgraphics(obj.ui_parent, 'figure')
                value = get(obj.ui_parent, 'Color');
            elseif isgraphics(obj.ui_parent, 'uipanel')
                value = get(obj.ui_parent, 'BackgroundColor');
            end
        end
        
        % mehtod :: unlockUI
        %  input :: class object
        % action :: unlocks user interface
        function obj = unlockUI(obj)
            set(obj.ui_pushButton_SegmentTree, 'Enable', 'on');
        end
        
        
        % method :: setFigureCallbacks
        %  input :: class object, setState
        % action :: switch on/off figure callbacks
        function obj = setFigureCallbacks(obj, setState)
            
            switch setState
                
                case 'on'
                    
                    set(obj.ih_figure,...
                        'WindowButtonMotionFcn', @obj.fcnCallback_MoveMouse,...
                        'WindowButtonDownFcn', @obj.fcnCallback_ClickDown,...
                        'WindowButtonUpFcn', @obj.fcnCallback_ClickUp,...
                        'WindowKeyPressFcn', @obj.fcnCallback_PressKey);
                    
                case 'off'
                    
                    set(obj.ih_figure,...
                        'WindowButtonMotionFcn', [],...
                        'WindowButtonDownFcn', [],...
                        'WindowButtonUpFcn', [],...
                        'WindowKeyPressFcn', []);
                    
            end
            
        end
        
        
        % method :: segmentTree
        %  input :: class object
        % action :: setting current figure callbacks
        function obj = segmentTree(obj)
            
           % set callback functions
           obj.setFigureCallbacks('on');
            
        end
        
        
        % method :: clearTree
        %  input :: class object
        % action :: clear current tree and figure callbacks
        function obj = clearTree(obj)
            
            % remove callback functions
            obj.setFigureCallbacks('off');
            
        end
        
        
        % method :: enableButtonGroup
        %  input :: class object, enable
        % action :: change operational state of button group
        function obj = enableButtonGroup(obj, enable)
            buttonGroup = cat(1,...
                obj.ui_pushButton_SaveTree,...
                obj.ui_pushButton_LoadTree,...
                obj.ui_pushButton_LinkTree,...
                obj.ui_pushButton_ViewMask,...
                obj.ui_pushButton_DownMask,...
                obj.ui_pushButton_UpMask);
            
            set(buttonGroup, 'Enable', enable);
        end
        
        
        
        %%% ----------------------------- %%%
        %%% --- UI CALLBACK FUNCTIONS --- %%%
        %%% ----------------------------- %%%
        
        % callback :: CloseUIWindow
        %    event :: on close request
        %   action :: class destructor
        function obj = fcnCallback_CloseUIWindow(obj, ~, ~)
            
            if isgraphics(obj.ui_parent)
                delete(obj.ui_parent);
            end
            
            delete(obj);
        end
        
        
        % callback :: SegmentTree
        %    event :: on segment button
        %   action :: initialize segmentation with current image
        function obj = fcnCallback_SegmentTree(obj, ~, ~)
            
            switch obj.ui_pushButton_SegmentTree.String
                
                case 'Segment'
                    set(obj.ui_pushButton_SegmentTree, 'String', 'Clear');
                    obj.enableButtonGroup('on');
                    obj.segmentTree();
                    
                case 'Clear'
                    set(obj.ui_pushButton_SegmentTree, 'String', 'Segment');
                    obj.enableButtonGroup('off');
                    obj.clearTree();
                    
            end
            
        end
        
        % callback :: SaveTree
        %    event :: on save tree button
        %   action :: exports current tree in txt format
        function obj = fcnCallback_SaveTree(obj, ~, ~)
            obj.saveTree();
        end

        
        % callback :: LoadTree
        %    event :: on load tree button
        %   action :: load exported neuro tree
        function obj = fcnCallback_LoadTree(obj, ~, ~)
            obj.loadTree();
        end
        
        % callback :: SetMaskSize
        %    event :: on mask Up/Down buttons
        %   action :: adjust mask size
        function obj = fcnCallback_SetMaskSize(obj, hSrc, ~)
            
            % update mask size
            switch hSrc
                case obj.ui_pushButton_DownMask
                    obj.dilate = obj.dilate - 1;
                case obj.ui_pushButton_UpMask
                    obj.dilate = obj.dilate + 1;
            end
            
            % set minimum size
            if (obj.dilate < obj.MIN_DILATE_SIZE + 1)
                set(obj.ui_pushButton_DownMask, 'Enable', 'off');
            else
                set(obj.ui_pushButton_DownMask, 'Enable', 'on');
            end
            
            % set maximum size
            if (obj.dilate > obj.MAX_DILATE_SIZE - 1)
                set(obj.ui_pushButton_UpMask, 'Enable', 'off');
            else
                set(obj.ui_pushButton_UpMask, 'Enable', 'on');
            end
            
            % update status
            set(obj.ui_text_StatusDilate, 'String', sprintf('dilate[px] %d',obj.dilate));
            
        end
        
    end
    
end
