function obj = uitabviewlimits(obj)

    %% --- add new tab to group --- %%
    tabViewLimit = uix.Panel('Parent', obj.panelTabs);
    obj.panelTabs.TabTitles(end) = {'view'};
    
    %% --- image navigation --- %%
    layoutViewLimit = uix.VBoxFlex(...
        'Parent', tabViewLimit);
    
    buttonGroup_pickClim = uix.HButtonBox(...
        'Parent', layoutViewLimit,...
        'Padding', obj.UI_GRID_PADDING,...
        'Spacing', obj.UI_GRID_SPACING,...
        'ButtonSize', obj.UI_BUTTON_SIZE);
    
    obj.popup_pickClim = uicontrol(...
        'Parent', buttonGroup_pickClim,...
        'Style', 'popup',...
        'String', obj.UI_POPUP_CHOOSE_CLIM);
    
    buttonGroup_editClim = uix.HButtonBox(...
        'Parent', layoutViewLimit,...
        'Padding', obj.UI_GRID_PADDING,...
        'Spacing', obj.UI_GRID_SPACING,...
        'ButtonSize', obj.UI_BUTTON_SIZE);
    
    uicontrol(...
        'Parent', buttonGroup_editClim,...
        'Style', 'text', ...
        'String', 'min');
    
    obj.editBox_minClim = uicontrol(...
        'Parent', buttonGroup_editClim,...
        'Style', 'edit',...
        'String', '0',...
        'Enable', 'off');
    
    obj.editBox_maxClim = uicontrol(...
        'Parent', buttonGroup_editClim,...
        'Style', 'edit',...
        'String', '1',...
        'Enable', 'off');
    
    uicontrol(...
        'Parent', buttonGroup_editClim,...
        'Style', 'text', ...
        'String', 'max');

end