classdef LSMLookupTable
  %LSMLOOKUPTABLE Class representation of a LookupTable in LSM files
  %
  % AUTHOR: Stefano Masneri
  % Date: 14.3.2017
  
  properties
    size;
    numberSubBlocks;  % Number of sub blocks (without the List End Marker sub block)
    numberChannels;   % Number of channels handled in the description block.
                      % For the color palette it must be 3 and for the input
                      % lookup table it must be the number of data channels.
    lutType;          % Most recently selected type of the LUT.
                      % LUT_NORMAL = 0 LUT generated by the brightness and contrast properties.
                      % LUT_ORIGINAL = 1 LUT generated by 12 bit to 12 bit LUT and the
                      %   brightness and contrast properties.
                      % LUT_RAMP = 2 LUT generated by a ramp defined by start and
                      %   end point, the brightness and the contrast properties.
                      % LUT_POLYLINE = 3 LUT generated by multiple lines, the 
                      %   brightness and the contrast properties.
                      % LUT_SPLINE = 4 LUT generated by a cubic spline curve, 
                      %   the brightness and the contrast properties.
                      % LUT_GAMMA = 5 LUT generated by an exponential function,
                      %   the brightness and the contrast properties (Not used in case of color palette).
    advanced;         % This flag is used for the input LUT and is unequal zero if the "More/Simple"
                      %   button in the "Brightness and Contrast" dialog was pressed.
    currentChannel;   % Zero based number of the channel that was most recently
                      %   selected for modifications in the LUT editor.
                      %   A value of -1 means all channels were selected.
    %subblocks. Each one is a structure, empty if not specified.
    gamma;
    brightness;
    contrast;
    ramp;
    knots;
    palette12To12;
  end
  
  properties (Constant = true)
    SUBBLOCK_GAMMA = 1;
    SUBBLOCK_BRIGHTNESS = 2;
    SUBBLOCK_CONTRAST = 3;
    SUBBLOCK_RAMP = 4;
    SUBBLOCK_KNOTS = 5;
    SUBBLOCK_PALETTE_12_TO_12 = 6;
    SUBBLOCK_LIST_END = 0;
  end
  
  methods
    function obj = LSMLookupTable(lsmPtr, byteOrder)
    %LSMLOOKUPTABLE Constructor
    % Assumes the file pointer in the correct position already
      obj.size = fread(lsmPtr, 1, 'uint32', byteOrder);
      obj.numberSubBlocks = fread(lsmPtr, 1, 'uint32', byteOrder);
      obj.numberChannels = fread(lsmPtr, 1, 'uint32', byteOrder);
      obj.lutType = fread(lsmPtr, 1, 'uint32', byteOrder);
      obj.advanced = fread(lsmPtr, 1, 'uint32', byteOrder);
      obj.currentChannel = fread(lsmPtr, 1, 'uint32', byteOrder);
      reserved = fread(lsmPtr, 9, 'uint32', byteOrder);
      if any(cane)
        error('LSMLookupTable: Error parsing from file')
      end
      % now read all the subblocks
      for k = 1:obj.numberSubBlocks
        type = fread(lsmPtr, 1, 'uint32', byteOrder);
        if type == obj.SUBBLOCK_GAMMA
        elseif type == obj.SUBBLOCK_BRIGHTNESS
        elseif type == obj.SUBBLOCK_CONTRAST
        elseif type == obj.SUBBLOCK_RAMP
        elseif type == obj.SUBBLOCK_KNOTS
        elseif type == obj.SUBBLOCK_LIST_END
        end
      end
      subblockEnd = fread(lsmPtr, 1, 'uint32', byteOrder);
      if subblockEnd ~= obj.SUBBLOCK_LIST_END
        error('LSMLookupTable: Error parsing from file')
      end
    end
  end
  
end

