function obj = uitabnavigate(obj)

    %% --- add new tab to group --- %%
    tabNavigate = uix.Panel('Parent', obj.panelTabs);
    obj.panelTabs.TabTitles(end) = {'navigate'};

    %% --- image navigation --- %%
    layoutNavigate = uiextras.VBoxFlex(...
        'Parent', tabNavigate);

    buttonGroup_channel = uix.HButtonBox(...
        'Parent', layoutNavigate,...
        'Padding', obj.UI_GRID_PADDING,...
        'Spacing', obj.UI_GRID_SPACING,...
        'ButtonSize', obj.UI_BUTTON_SIZE);

    obj.text_counterChannel = uicontrol(...
        'Parent', buttonGroup_channel,...
        'Style', 'text',...
        'String', 'channel 1 / 1');    

    obj.pushButton_prevChannel = uicontrol(...
        'Parent', buttonGroup_channel,...
        'Style', 'pushbutton',...
        'String', '<<',...
        'Enable', 'on');

    obj.pushButton_nextChannel = uicontrol(...
        'Parent', buttonGroup_channel,...
        'Style', 'pushbutton',...
        'String', '>>',...
        'Enable', 'on');

    buttonGroup_stack = uix.HButtonBox(...
        'Parent', layoutNavigate,...
        'Padding', obj.UI_GRID_PADDING,...
        'Spacing', obj.UI_GRID_SPACING,...
        'ButtonSize', obj.UI_BUTTON_SIZE);

    obj.text_counterStack = uicontrol(...
        'Parent', buttonGroup_stack,...
        'Style', 'text',...
        'String', 'stack 1 / 1');    

    obj.pushButton_prevStack = uicontrol(...
        'Parent', buttonGroup_stack,...
        'Style', 'pushbutton',...
        'String', '<<',...
        'Enable', 'on');

    obj.pushButton_nextStack = uicontrol(...
        'Parent', buttonGroup_stack,...
        'Style', 'pushbutton',...
        'String', '>>',...
        'Enable', 'on');


end
