function obj = uitabproject(obj)

    %% --- add new tab to group --- %%
    tabProject = uix.Panel('Parent', obj.panelTabs);
    obj.panelTabs.TabTitles(end) = {'project'};
    
    %% --- image projection --- %%
    layoutProject = uix.VBoxFlex(...
        'Parent', tabProject);
    
    buttonGroup_popup = uix.HButtonBox(...
        'Parent', layoutProject,...
        'Padding', obj.UI_GRID_PADDING,...
        'Spacing', obj.UI_GRID_SPACING,...
        'ButtonSize', obj.UI_BUTTON_SIZE);
    
    obj.popup_pickProjection = uicontrol(...
        'Parent', buttonGroup_popup,...
        'Style', 'popup',...
        'String', obj.UI_POPUP_CHOOSE_PROJECTION);
    
    buttonGroup_click = uix.HButtonBox(...
        'Parent', layoutProject,...
        'Padding', obj.UI_GRID_PADDING,...
        'Spacing', obj.UI_GRID_SPACING,...
        'ButtonSize', obj.UI_BUTTON_SIZE);
    
    obj.pushButton_project = uicontrol(...
        'Parent', buttonGroup_click,...
        'Style', 'pushbutton',...
        'String', 'project');
    
    obj.checkBox_keepProjection = uicontrol(...
        'Parent', buttonGroup_click,...
        'Style', 'checkbox',...
        'String', 'keep',...
        'Value', 0);
    

end
